# Render Blueprint for YonEarth Gaia Chatbot
services:
  - type: web
    name: yonearth-gaia-chat
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab'); nltk.download('stopwords')"
    startCommand: "uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    
    # Environment variables
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # User must enter their own key
      - key: OPENAI_MODEL
        value: gpt-3.5-turbo
      - key: OPENAI_EMBEDDING_MODEL
        value: text-embedding-3-small
      
      - key: PINECONE_API_KEY
        sync: false  # User must enter their own key
      - key: PINECONE_ENVIRONMENT
        value: gcp-starter
      - key: PINECONE_INDEX_NAME
        value: yonearth-episodes
      
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        fromGroup: $PORT
      - key: API_RELOAD
        value: false
      
      - key: ALLOWED_ORIGINS
        value: https://yonearth.org,http://localhost:3000
      
      - key: RATE_LIMIT_PER_MINUTE
        value: 10
      
      - key: LOG_LEVEL
        value: INFO
      
      - key: GAIA_PERSONALITY_VARIANT
        value: warm_mother
      - key: GAIA_TEMPERATURE
        value: 0.7
      - key: GAIA_MAX_TOKENS
        value: 1000
      
      - key: EPISODES_TO_PROCESS
        value: 172
      - key: CHUNK_SIZE
        value: 500
      - key: CHUNK_OVERLAP
        value: 50
      
      - key: DEBUG
        value: false
      
      # Redis will be added automatically by Render if Redis service is included
      - key: REDIS_URL
        value: redis://localhost:6379  # Default for basic deployment without Redis service

  # Optional Redis service for caching (remove to save $7/month for basic deployment)
  # - type: redis
  #   name: yonearth-redis
  #   plan: starter  # $7/month
  #   maxmemoryPolicy: allkeys-lru