#!/usr/bin/env python3
"""
Apply V12 changeset generated by Curator.

Uses the intelligent Applicator to transform strategic guidance into actual code changes.
This script applies all changes from the V11.2.2 → V12 changeset.
"""

import json
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

# Load environment variables FIRST
from dotenv import load_dotenv
load_dotenv()

from src.ace_kg.kg_curator import KGCuratorAgent


def main():
    print("="*80)
    print("🔧 APPLYING V12 CHANGESET")
    print("="*80)
    print()

    # Load the latest V12 changeset
    changeset_path = Path("/home/claudeuser/yonearth-gaia-chatbot/kg_extraction_playbook/changesets/changeset_v11_to_v12_20251014_020533.json")

    if not changeset_path.exists():
        print(f"❌ Changeset not found: {changeset_path}")
        return

    print(f"📂 Loading V12 changeset...")
    with open(changeset_path) as f:
        changeset = json.load(f)

    print(f"✅ Loaded changeset:")
    print(f"   - Source version: {changeset['metadata']['source_version']}")
    print(f"   - Target version: {changeset['metadata']['target_version']}")
    print(f"   - Total operations: {len(changeset.get('file_operations', []))}")
    print()

    # Display operations
    print("📋 CHANGESET OPERATIONS:")
    for i, op in enumerate(changeset.get('file_operations', []), 1):
        priority = op.get('priority', 'UNKNOWN')
        op_type = op.get('operation_type', 'UNKNOWN')
        file_path = op.get('file_path', 'unknown')
        print(f"  {i}. [{priority}] {op_type}: {file_path}")
    print()

    # Initialize Curator (which has the Applicator)
    print("🤖 Initializing Curator's Intelligent Applicator...")
    curator = KGCuratorAgent()
    print()

    # Apply changeset
    print("="*80)
    print("⚡ APPLYING CHANGES")
    print("="*80)
    print()
    print("This will take 5-10 minutes as each change uses Claude to generate code...")
    print()

    # Apply with auto_apply_low_risk=True (all changes are marked low risk)
    results = curator.apply_changeset(
        changeset=changeset,
        dry_run=False,
        auto_apply_low_risk=True
    )

    print()
    print("="*80)
    print("✅ V12 CHANGESET APPLICATION COMPLETE")
    print("="*80)
    print()

    # Summary
    print("📊 APPLICATION RESULTS:")
    print(f"   - ✅ Applied: {len(results['applied'])}")
    print(f"   - ⏸️  Requires approval: {len(results['requires_approval'])}")
    print(f"   - ⏭️  Skipped: {len(results['skipped'])}")
    print(f"   - ❌ Failed: {len(results['failed'])}")
    print()

    if results['failed']:
        print("❌ FAILED OPERATIONS:")
        for fail in results['failed']:
            op = fail['operation']
            error = fail['error']
            print(f"   - {op.get('operation_id')}: {error}")
        print()

    if results['requires_approval']:
        print("⏸️  OPERATIONS REQUIRING MANUAL APPROVAL:")
        for op in results['requires_approval']:
            print(f"   - {op.get('operation_id')} [{op.get('priority')}]: {op.get('file_path')}")
        print()

    # Next steps
    print("="*80)
    print("🎯 NEXT STEPS")
    print("="*80)
    print()

    if len(results['applied']) == len(changeset.get('file_operations', [])):
        print("🎉 ALL CHANGES APPLIED SUCCESSFULLY!")
        print()
        print("1. ✅ V12 code and prompts are now in place")
        print("2. 📊 Run V12 extraction to test improvements:")
        print("   python scripts/extract_kg_v12_book.py")
        print()
        print("3. 🔍 Run Reflector on V12 results:")
        print("   python scripts/run_reflector_on_v12.py")
        print()
        print("4. 📈 Compare quality: V11.2.2 (7.86% errors) → V12 (target: <4% errors)")
    else:
        print("⚠️  Some changes require attention:")
        print()
        if results['failed']:
            print("1. Review failed operations above")
            print("2. Fix issues and re-apply")
        if results['requires_approval']:
            print("1. Review operations requiring approval")
            print("2. Manually apply or adjust risk settings")

    print("="*80)


if __name__ == "__main__":
    main()
